--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test_deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: test_service
  template:
    metadata: 
      labels:
        app: test_service
    spec:
      containers:
      - name: test_service
        image: "{{ .Values.image }}"
